/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PublicRouteImport } from "./routes/public"
import { Route as CustomerRouteImport } from "./routes/customer"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as RouteRouteImport } from "./routes/route"
import { Route as PublicAboutRouteImport } from "./routes/public/about"
import { Route as CustomerCheckoutRouteImport } from "./routes/customer/checkout"
import { Route as CustomerCartRouteImport } from "./routes/customer/cart"
import { Route as AuthRegisterRouteImport } from "./routes/_auth/register"
import { Route as AuthProfileRouteImport } from "./routes/_auth/profile"
import { Route as AuthLoginRouteImport } from "./routes/_auth/login"
import { Route as PublicProductsIndexRouteImport } from "./routes/public/products/index"
import { Route as PublicProductsProductIdRouteImport } from "./routes/public/products/$productId"
import { Route as CustomerOrdersManageRouteImport } from "./routes/customer/orders/manage"
import { Route as CustomerOrdersOrderIdRouteImport } from "./routes/customer/orders/$orderId"
import { Route as AdminManageUsersRouteImport } from "./routes/admin/manage/users"
import { Route as AdminManageStoreSettingsRouteImport } from "./routes/admin/manage/storeSettings"
import { Route as AdminManageReportsRouteImport } from "./routes/admin/manage/reports"
import { Route as AdminManageDashboardRouteImport } from "./routes/admin/manage/dashboard"
import { Route as AdminManageAuditLogsRouteImport } from "./routes/admin/manage/auditLogs"
import { Route as AdminManageOrdersIndexRouteImport } from "./routes/admin/manage/orders/index"
import { Route as AdminManageInventoryIndexRouteImport } from "./routes/admin/manage/inventory/index"
import { Route as AdminManageOrdersOrderIdRouteImport } from "./routes/admin/manage/orders/$orderId"
import { Route as AdminManageInventoryImportRouteImport } from "./routes/admin/manage/inventory/import"
import { Route as AdminManageInventoryAddRouteImport } from "./routes/admin/manage/inventory/add"
import { Route as AdminManageInventoryInventoryIdRouteImport } from "./routes/admin/manage/inventory/$inventoryId"
import { Route as AdminManageInventoryEditProductIdRouteImport } from "./routes/admin/manage/inventory/edit/$productId"

const PublicRoute = PublicRouteImport.update({
  id: "/public",
  path: "/public",
  getParentRoute: () => rootRouteImport,
})
const CustomerRoute = CustomerRouteImport.update({
  id: "/customer",
  path: "/customer",
  getParentRoute: () => rootRouteImport,
})
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
})
const RouteRoute = RouteRouteImport.update({
  id: "/",
  path: "",
  getParentRoute: () => rootRouteImport,
})
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => PublicRoute,
})
const CustomerCheckoutRoute = CustomerCheckoutRouteImport.update({
  id: "/checkout",
  path: "/checkout",
  getParentRoute: () => CustomerRoute,
})
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: "/cart",
  path: "/cart",
  getParentRoute: () => CustomerRoute,
})
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/_auth/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
})
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: "/_auth/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
})
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/_auth/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
})
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: "/products/",
  path: "/products/",
  getParentRoute: () => PublicRoute,
})
const PublicProductsProductIdRoute = PublicProductsProductIdRouteImport.update({
  id: "/products/$productId",
  path: "/products/$productId",
  getParentRoute: () => PublicRoute,
})
const CustomerOrdersManageRoute = CustomerOrdersManageRouteImport.update({
  id: "/orders/manage",
  path: "/orders/manage",
  getParentRoute: () => CustomerRoute,
})
const CustomerOrdersOrderIdRoute = CustomerOrdersOrderIdRouteImport.update({
  id: "/orders/$orderId",
  path: "/orders/$orderId",
  getParentRoute: () => CustomerRoute,
})
const AdminManageUsersRoute = AdminManageUsersRouteImport.update({
  id: "/manage/users",
  path: "/manage/users",
  getParentRoute: () => AdminRoute,
})
const AdminManageStoreSettingsRoute =
  AdminManageStoreSettingsRouteImport.update({
    id: "/manage/storeSettings",
    path: "/manage/storeSettings",
    getParentRoute: () => AdminRoute,
  })
const AdminManageReportsRoute = AdminManageReportsRouteImport.update({
  id: "/manage/reports",
  path: "/manage/reports",
  getParentRoute: () => AdminRoute,
})
const AdminManageDashboardRoute = AdminManageDashboardRouteImport.update({
  id: "/manage/dashboard",
  path: "/manage/dashboard",
  getParentRoute: () => AdminRoute,
})
const AdminManageAuditLogsRoute = AdminManageAuditLogsRouteImport.update({
  id: "/manage/auditLogs",
  path: "/manage/auditLogs",
  getParentRoute: () => AdminRoute,
})
const AdminManageOrdersIndexRoute = AdminManageOrdersIndexRouteImport.update({
  id: "/manage/orders/",
  path: "/manage/orders/",
  getParentRoute: () => AdminRoute,
})
const AdminManageInventoryIndexRoute =
  AdminManageInventoryIndexRouteImport.update({
    id: "/manage/inventory/",
    path: "/manage/inventory/",
    getParentRoute: () => AdminRoute,
  })
const AdminManageOrdersOrderIdRoute =
  AdminManageOrdersOrderIdRouteImport.update({
    id: "/manage/orders/$orderId",
    path: "/manage/orders/$orderId",
    getParentRoute: () => AdminRoute,
  })
const AdminManageInventoryImportRoute =
  AdminManageInventoryImportRouteImport.update({
    id: "/manage/inventory/import",
    path: "/manage/inventory/import",
    getParentRoute: () => AdminRoute,
  })
const AdminManageInventoryAddRoute = AdminManageInventoryAddRouteImport.update({
  id: "/manage/inventory/add",
  path: "/manage/inventory/add",
  getParentRoute: () => AdminRoute,
})
const AdminManageInventoryInventoryIdRoute =
  AdminManageInventoryInventoryIdRouteImport.update({
    id: "/manage/inventory/$inventoryId",
    path: "/manage/inventory/$inventoryId",
    getParentRoute: () => AdminRoute,
  })
const AdminManageInventoryEditProductIdRoute =
  AdminManageInventoryEditProductIdRouteImport.update({
    id: "/manage/inventory/edit/$productId",
    path: "/manage/inventory/edit/$productId",
    getParentRoute: () => AdminRoute,
  })

const AdminRouteChildren = {
  AdminManageAuditLogsRoute: AdminManageAuditLogsRoute,
  AdminManageDashboardRoute: AdminManageDashboardRoute,
  AdminManageReportsRoute: AdminManageReportsRoute,
  AdminManageStoreSettingsRoute: AdminManageStoreSettingsRoute,
  AdminManageUsersRoute: AdminManageUsersRoute,
  AdminManageInventoryInventoryIdRoute: AdminManageInventoryInventoryIdRoute,
  AdminManageInventoryAddRoute: AdminManageInventoryAddRoute,
  AdminManageInventoryImportRoute: AdminManageInventoryImportRoute,
  AdminManageOrdersOrderIdRoute: AdminManageOrdersOrderIdRoute,
  AdminManageInventoryIndexRoute: AdminManageInventoryIndexRoute,
  AdminManageOrdersIndexRoute: AdminManageOrdersIndexRoute,
  AdminManageInventoryEditProductIdRoute:
    AdminManageInventoryEditProductIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const CustomerRouteChildren = {
  CustomerCartRoute: CustomerCartRoute,
  CustomerCheckoutRoute: CustomerCheckoutRoute,
  CustomerOrdersOrderIdRoute: CustomerOrdersOrderIdRoute,
  CustomerOrdersManageRoute: CustomerOrdersManageRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicProductsProductIdRoute: PublicProductsProductIdRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren = {
  RouteRoute: RouteRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
