/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductDetailRouteImport } from './routes/productDetail'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as OrdersManageRouteImport } from './routes/orders/manage'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as ManageOrdersRouteImport } from './routes/manage/orders'
import { Route as ManageInventoryRouteImport } from './routes/manage/inventory'
import { Route as ManageDashboardRouteImport } from './routes/manage/dashboard'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const ProductDetailRoute = ProductDetailRouteImport.update({
  id: '/productDetail',
  path: '/productDetail',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersManageRoute = OrdersManageRouteImport.update({
  id: '/orders/manage',
  path: '/orders/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageOrdersRoute = ManageOrdersRouteImport.update({
  id: '/manage/orders',
  path: '/manage/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageInventoryRoute = ManageInventoryRouteImport.update({
  id: '/manage/inventory',
  path: '/manage/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDashboardRoute = ManageDashboardRouteImport.update({
  id: '/manage/dashboard',
  path: '/manage/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/_auth/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/productDetail': typeof ProductDetailRoute
  '/login': typeof AuthLoginRoute
  '/profile': typeof AuthProfileRoute
  '/register': typeof AuthRegisterRoute
  '/manage/dashboard': typeof ManageDashboardRoute
  '/manage/inventory': typeof ManageInventoryRoute
  '/manage/orders': typeof ManageOrdersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/manage': typeof OrdersManageRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/productDetail': typeof ProductDetailRoute
  '/login': typeof AuthLoginRoute
  '/profile': typeof AuthProfileRoute
  '/register': typeof AuthRegisterRoute
  '/manage/dashboard': typeof ManageDashboardRoute
  '/manage/inventory': typeof ManageInventoryRoute
  '/manage/orders': typeof ManageOrdersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/manage': typeof OrdersManageRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/productDetail': typeof ProductDetailRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/manage/dashboard': typeof ManageDashboardRoute
  '/manage/inventory': typeof ManageInventoryRoute
  '/manage/orders': typeof ManageOrdersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/manage': typeof OrdersManageRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/productDetail'
    | '/login'
    | '/profile'
    | '/register'
    | '/manage/dashboard'
    | '/manage/inventory'
    | '/manage/orders'
    | '/orders/$orderId'
    | '/orders/manage'
    | '/products/$productId'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/productDetail'
    | '/login'
    | '/profile'
    | '/register'
    | '/manage/dashboard'
    | '/manage/inventory'
    | '/manage/orders'
    | '/orders/$orderId'
    | '/orders/manage'
    | '/products/$productId'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/productDetail'
    | '/_auth/login'
    | '/_auth/profile'
    | '/_auth/register'
    | '/manage/dashboard'
    | '/manage/inventory'
    | '/manage/orders'
    | '/orders/$orderId'
    | '/orders/manage'
    | '/products/$productId'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ProductDetailRoute: typeof ProductDetailRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ManageDashboardRoute: typeof ManageDashboardRoute
  ManageInventoryRoute: typeof ManageInventoryRoute
  ManageOrdersRoute: typeof ManageOrdersRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersManageRoute: typeof OrdersManageRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productDetail': {
      id: '/productDetail'
      path: '/productDetail'
      fullPath: '/productDetail'
      preLoaderRoute: typeof ProductDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/manage': {
      id: '/orders/manage'
      path: '/orders/manage'
      fullPath: '/orders/manage'
      preLoaderRoute: typeof OrdersManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/orders': {
      id: '/manage/orders'
      path: '/manage/orders'
      fullPath: '/manage/orders'
      preLoaderRoute: typeof ManageOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/inventory': {
      id: '/manage/inventory'
      path: '/manage/inventory'
      fullPath: '/manage/inventory'
      preLoaderRoute: typeof ManageInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/dashboard': {
      id: '/manage/dashboard'
      path: '/manage/dashboard'
      fullPath: '/manage/dashboard'
      preLoaderRoute: typeof ManageDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ProductDetailRoute: ProductDetailRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ManageDashboardRoute: ManageDashboardRoute,
  ManageInventoryRoute: ManageInventoryRoute,
  ManageOrdersRoute: ManageOrdersRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersManageRoute: OrdersManageRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
