/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteRouteImport } from './routes/public/route'
import { Route as RouteRouteImport } from './routes/route'
import { Route as PublicHomeRouteImport } from './routes/public/home'
import { Route as PublicContactRouteImport } from './routes/public/contact'
import { Route as PublicAboutRouteImport } from './routes/public/about'
import { Route as CustomerProfileRouteImport } from './routes/customer/profile'
import { Route as CustomerCheckoutRouteImport } from './routes/customer/checkout'
import { Route as CustomerCartRouteImport } from './routes/customer/cart'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as PublicProductsIndexRouteImport } from './routes/public/products/index'
import { Route as PublicProductsProductIdRouteImport } from './routes/public/products/$productId'
import { Route as CustomerOrdersManageRouteImport } from './routes/customer/orders/manage'
import { Route as CustomerOrdersOrderIdRouteImport } from './routes/customer/orders/$orderId'
import { Route as AdminManageUsersRouteImport } from './routes/admin/manage/users'
import { Route as AdminManageStoreSettingsRouteImport } from './routes/admin/manage/storeSettings'
import { Route as AdminManageReportsRouteImport } from './routes/admin/manage/reports'
import { Route as AdminManageDashboardRouteImport } from './routes/admin/manage/dashboard'
import { Route as AdminManageAuditLogsRouteImport } from './routes/admin/manage/auditLogs'
import { Route as AdminManageOrdersIndexRouteImport } from './routes/admin/manage/orders/index'
import { Route as AdminManageInventoryIndexRouteImport } from './routes/admin/manage/inventory/index'
import { Route as AdminManageOrdersOrderIdRouteImport } from './routes/admin/manage/orders/$orderId'
import { Route as AdminManageInventoryImportRouteImport } from './routes/admin/manage/inventory/import'
import { Route as AdminManageInventoryAddRouteImport } from './routes/admin/manage/inventory/add'
import { Route as AdminManageInventoryInventoryIdRouteImport } from './routes/admin/manage/inventory/$inventoryId'
import { Route as AdminManageInventoryEditProductIdRouteImport } from './routes/admin/manage/inventory/edit/$productId'

const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicHomeRoute = PublicHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCheckoutRoute = CustomerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CustomerRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProductsProductIdRoute = PublicProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => PublicRouteRoute,
} as any)
const CustomerOrdersManageRoute = CustomerOrdersManageRouteImport.update({
  id: '/orders/manage',
  path: '/orders/manage',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrdersOrderIdRoute = CustomerOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminManageUsersRoute = AdminManageUsersRouteImport.update({
  id: '/manage/users',
  path: '/manage/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageStoreSettingsRoute =
  AdminManageStoreSettingsRouteImport.update({
    id: '/manage/storeSettings',
    path: '/manage/storeSettings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminManageReportsRoute = AdminManageReportsRouteImport.update({
  id: '/manage/reports',
  path: '/manage/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageDashboardRoute = AdminManageDashboardRouteImport.update({
  id: '/manage/dashboard',
  path: '/manage/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageAuditLogsRoute = AdminManageAuditLogsRouteImport.update({
  id: '/manage/auditLogs',
  path: '/manage/auditLogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageOrdersIndexRoute = AdminManageOrdersIndexRouteImport.update({
  id: '/manage/orders/',
  path: '/manage/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageInventoryIndexRoute =
  AdminManageInventoryIndexRouteImport.update({
    id: '/manage/inventory/',
    path: '/manage/inventory/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminManageOrdersOrderIdRoute =
  AdminManageOrdersOrderIdRouteImport.update({
    id: '/manage/orders/$orderId',
    path: '/manage/orders/$orderId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminManageInventoryImportRoute =
  AdminManageInventoryImportRouteImport.update({
    id: '/manage/inventory/import',
    path: '/manage/inventory/import',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminManageInventoryAddRoute = AdminManageInventoryAddRouteImport.update({
  id: '/manage/inventory/add',
  path: '/manage/inventory/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageInventoryInventoryIdRoute =
  AdminManageInventoryInventoryIdRouteImport.update({
    id: '/manage/inventory/$inventoryId',
    path: '/manage/inventory/$inventoryId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminManageInventoryEditProductIdRoute =
  AdminManageInventoryEditProductIdRouteImport.update({
    id: '/manage/inventory/edit/$productId',
    path: '/manage/inventory/edit/$productId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/public/about': typeof PublicAboutRoute
  '/public/contact': typeof PublicContactRoute
  '/public/home': typeof PublicHomeRoute
  '/admin/manage/auditLogs': typeof AdminManageAuditLogsRoute
  '/admin/manage/dashboard': typeof AdminManageDashboardRoute
  '/admin/manage/reports': typeof AdminManageReportsRoute
  '/admin/manage/storeSettings': typeof AdminManageStoreSettingsRoute
  '/admin/manage/users': typeof AdminManageUsersRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/customer/orders/manage': typeof CustomerOrdersManageRoute
  '/public/products/$productId': typeof PublicProductsProductIdRoute
  '/public/products': typeof PublicProductsIndexRoute
  '/admin/manage/inventory/$inventoryId': typeof AdminManageInventoryInventoryIdRoute
  '/admin/manage/inventory/add': typeof AdminManageInventoryAddRoute
  '/admin/manage/inventory/import': typeof AdminManageInventoryImportRoute
  '/admin/manage/orders/$orderId': typeof AdminManageOrdersOrderIdRoute
  '/admin/manage/inventory': typeof AdminManageInventoryIndexRoute
  '/admin/manage/orders': typeof AdminManageOrdersIndexRoute
  '/admin/manage/inventory/edit/$productId': typeof AdminManageInventoryEditProductIdRoute
}
export interface FileRoutesByTo {
  '/public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/public/about': typeof PublicAboutRoute
  '/public/contact': typeof PublicContactRoute
  '/public/home': typeof PublicHomeRoute
  '/admin/manage/auditLogs': typeof AdminManageAuditLogsRoute
  '/admin/manage/dashboard': typeof AdminManageDashboardRoute
  '/admin/manage/reports': typeof AdminManageReportsRoute
  '/admin/manage/storeSettings': typeof AdminManageStoreSettingsRoute
  '/admin/manage/users': typeof AdminManageUsersRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/customer/orders/manage': typeof CustomerOrdersManageRoute
  '/public/products/$productId': typeof PublicProductsProductIdRoute
  '/public/products': typeof PublicProductsIndexRoute
  '/admin/manage/inventory/$inventoryId': typeof AdminManageInventoryInventoryIdRoute
  '/admin/manage/inventory/add': typeof AdminManageInventoryAddRoute
  '/admin/manage/inventory/import': typeof AdminManageInventoryImportRoute
  '/admin/manage/orders/$orderId': typeof AdminManageOrdersOrderIdRoute
  '/admin/manage/inventory': typeof AdminManageInventoryIndexRoute
  '/admin/manage/orders': typeof AdminManageOrdersIndexRoute
  '/admin/manage/inventory/edit/$productId': typeof AdminManageInventoryEditProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof RouteRoute
  '/public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/public/about': typeof PublicAboutRoute
  '/public/contact': typeof PublicContactRoute
  '/public/home': typeof PublicHomeRoute
  '/admin/manage/auditLogs': typeof AdminManageAuditLogsRoute
  '/admin/manage/dashboard': typeof AdminManageDashboardRoute
  '/admin/manage/reports': typeof AdminManageReportsRoute
  '/admin/manage/storeSettings': typeof AdminManageStoreSettingsRoute
  '/admin/manage/users': typeof AdminManageUsersRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/customer/orders/manage': typeof CustomerOrdersManageRoute
  '/public/products/$productId': typeof PublicProductsProductIdRoute
  '/public/products/': typeof PublicProductsIndexRoute
  '/admin/manage/inventory/$inventoryId': typeof AdminManageInventoryInventoryIdRoute
  '/admin/manage/inventory/add': typeof AdminManageInventoryAddRoute
  '/admin/manage/inventory/import': typeof AdminManageInventoryImportRoute
  '/admin/manage/orders/$orderId': typeof AdminManageOrdersOrderIdRoute
  '/admin/manage/inventory/': typeof AdminManageInventoryIndexRoute
  '/admin/manage/orders/': typeof AdminManageOrdersIndexRoute
  '/admin/manage/inventory/edit/$productId': typeof AdminManageInventoryEditProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/public'
    | '/admin'
    | '/customer'
    | '/login'
    | '/register'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/profile'
    | '/public/about'
    | '/public/contact'
    | '/public/home'
    | '/admin/manage/auditLogs'
    | '/admin/manage/dashboard'
    | '/admin/manage/reports'
    | '/admin/manage/storeSettings'
    | '/admin/manage/users'
    | '/customer/orders/$orderId'
    | '/customer/orders/manage'
    | '/public/products/$productId'
    | '/public/products'
    | '/admin/manage/inventory/$inventoryId'
    | '/admin/manage/inventory/add'
    | '/admin/manage/inventory/import'
    | '/admin/manage/orders/$orderId'
    | '/admin/manage/inventory'
    | '/admin/manage/orders'
    | '/admin/manage/inventory/edit/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/public'
    | '/admin'
    | '/customer'
    | '/login'
    | '/register'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/profile'
    | '/public/about'
    | '/public/contact'
    | '/public/home'
    | '/admin/manage/auditLogs'
    | '/admin/manage/dashboard'
    | '/admin/manage/reports'
    | '/admin/manage/storeSettings'
    | '/admin/manage/users'
    | '/customer/orders/$orderId'
    | '/customer/orders/manage'
    | '/public/products/$productId'
    | '/public/products'
    | '/admin/manage/inventory/$inventoryId'
    | '/admin/manage/inventory/add'
    | '/admin/manage/inventory/import'
    | '/admin/manage/orders/$orderId'
    | '/admin/manage/inventory'
    | '/admin/manage/orders'
    | '/admin/manage/inventory/edit/$productId'
  id:
    | '__root__'
    | '/'
    | '/public'
    | '/admin'
    | '/customer'
    | '/_auth/login'
    | '/_auth/register'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/profile'
    | '/public/about'
    | '/public/contact'
    | '/public/home'
    | '/admin/manage/auditLogs'
    | '/admin/manage/dashboard'
    | '/admin/manage/reports'
    | '/admin/manage/storeSettings'
    | '/admin/manage/users'
    | '/customer/orders/$orderId'
    | '/customer/orders/manage'
    | '/public/products/$productId'
    | '/public/products/'
    | '/admin/manage/inventory/$inventoryId'
    | '/admin/manage/inventory/add'
    | '/admin/manage/inventory/import'
    | '/admin/manage/orders/$orderId'
    | '/admin/manage/inventory/'
    | '/admin/manage/orders/'
    | '/admin/manage/inventory/edit/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/home': {
      id: '/public/home'
      path: '/home'
      fullPath: '/public/home'
      preLoaderRoute: typeof PublicHomeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/public/contact': {
      id: '/public/contact'
      path: '/contact'
      fullPath: '/public/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/public/about': {
      id: '/public/about'
      path: '/about'
      fullPath: '/public/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/checkout': {
      id: '/customer/checkout'
      path: '/checkout'
      fullPath: '/customer/checkout'
      preLoaderRoute: typeof CustomerCheckoutRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/cart': {
      id: '/customer/cart'
      path: '/cart'
      fullPath: '/customer/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/products/': {
      id: '/public/products/'
      path: '/products'
      fullPath: '/public/products'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/public/products/$productId': {
      id: '/public/products/$productId'
      path: '/products/$productId'
      fullPath: '/public/products/$productId'
      preLoaderRoute: typeof PublicProductsProductIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/customer/orders/manage': {
      id: '/customer/orders/manage'
      path: '/orders/manage'
      fullPath: '/customer/orders/manage'
      preLoaderRoute: typeof CustomerOrdersManageRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/orders/$orderId': {
      id: '/customer/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/customer/orders/$orderId'
      preLoaderRoute: typeof CustomerOrdersOrderIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/manage/users': {
      id: '/admin/manage/users'
      path: '/manage/users'
      fullPath: '/admin/manage/users'
      preLoaderRoute: typeof AdminManageUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage/storeSettings': {
      id: '/admin/manage/storeSettings'
      path: '/manage/storeSettings'
      fullPath: '/admin/manage/storeSettings'
      preLoaderRoute: typeof AdminManageStoreSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage/reports': {
      id: '/admin/manage/reports'
      path: '/manage/reports'
      fullPath: '/admin/manage/reports'
      preLoaderRoute: typeof AdminManageReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage/dashboard': {
      id: '/admin/manage/dashboard'
      path: '/manage/dashboard'
      fullPath: '/admin/manage/dashboard'
      preLoaderRoute: typeof AdminManageDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage/auditLogs': {
      id: '/admin/manage/auditLogs'
      path: '/manage/auditLogs'
      fullPath: '/admin/manage/auditLogs'
      preLoaderRoute: typeof AdminManageAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage/orders/': {
      id: '/admin/manage/orders/'
      path: '/manage/orders'
      fullPath: '/admin/manage/orders'
      preLoaderRoute: typeof AdminManageOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage/inventory/': {
      id: '/admin/manage/inventory/'
      path: '/manage/inventory'
      fullPath: '/admin/manage/inventory'
      preLoaderRoute: typeof AdminManageInventoryIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage/orders/$orderId': {
      id: '/admin/manage/orders/$orderId'
      path: '/manage/orders/$orderId'
      fullPath: '/admin/manage/orders/$orderId'
      preLoaderRoute: typeof AdminManageOrdersOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage/inventory/import': {
      id: '/admin/manage/inventory/import'
      path: '/manage/inventory/import'
      fullPath: '/admin/manage/inventory/import'
      preLoaderRoute: typeof AdminManageInventoryImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage/inventory/add': {
      id: '/admin/manage/inventory/add'
      path: '/manage/inventory/add'
      fullPath: '/admin/manage/inventory/add'
      preLoaderRoute: typeof AdminManageInventoryAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage/inventory/$inventoryId': {
      id: '/admin/manage/inventory/$inventoryId'
      path: '/manage/inventory/$inventoryId'
      fullPath: '/admin/manage/inventory/$inventoryId'
      preLoaderRoute: typeof AdminManageInventoryInventoryIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage/inventory/edit/$productId': {
      id: '/admin/manage/inventory/edit/$productId'
      path: '/manage/inventory/edit/$productId'
      fullPath: '/admin/manage/inventory/edit/$productId'
      preLoaderRoute: typeof AdminManageInventoryEditProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicHomeRoute: typeof PublicHomeRoute
  PublicProductsProductIdRoute: typeof PublicProductsProductIdRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicHomeRoute: PublicHomeRoute,
  PublicProductsProductIdRoute: PublicProductsProductIdRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminRouteChildren {
  AdminManageAuditLogsRoute: typeof AdminManageAuditLogsRoute
  AdminManageDashboardRoute: typeof AdminManageDashboardRoute
  AdminManageReportsRoute: typeof AdminManageReportsRoute
  AdminManageStoreSettingsRoute: typeof AdminManageStoreSettingsRoute
  AdminManageUsersRoute: typeof AdminManageUsersRoute
  AdminManageInventoryInventoryIdRoute: typeof AdminManageInventoryInventoryIdRoute
  AdminManageInventoryAddRoute: typeof AdminManageInventoryAddRoute
  AdminManageInventoryImportRoute: typeof AdminManageInventoryImportRoute
  AdminManageOrdersOrderIdRoute: typeof AdminManageOrdersOrderIdRoute
  AdminManageInventoryIndexRoute: typeof AdminManageInventoryIndexRoute
  AdminManageOrdersIndexRoute: typeof AdminManageOrdersIndexRoute
  AdminManageInventoryEditProductIdRoute: typeof AdminManageInventoryEditProductIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminManageAuditLogsRoute: AdminManageAuditLogsRoute,
  AdminManageDashboardRoute: AdminManageDashboardRoute,
  AdminManageReportsRoute: AdminManageReportsRoute,
  AdminManageStoreSettingsRoute: AdminManageStoreSettingsRoute,
  AdminManageUsersRoute: AdminManageUsersRoute,
  AdminManageInventoryInventoryIdRoute: AdminManageInventoryInventoryIdRoute,
  AdminManageInventoryAddRoute: AdminManageInventoryAddRoute,
  AdminManageInventoryImportRoute: AdminManageInventoryImportRoute,
  AdminManageOrdersOrderIdRoute: AdminManageOrdersOrderIdRoute,
  AdminManageInventoryIndexRoute: AdminManageInventoryIndexRoute,
  AdminManageOrdersIndexRoute: AdminManageOrdersIndexRoute,
  AdminManageInventoryEditProductIdRoute:
    AdminManageInventoryEditProductIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerCheckoutRoute: typeof CustomerCheckoutRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerOrdersOrderIdRoute: typeof CustomerOrdersOrderIdRoute
  CustomerOrdersManageRoute: typeof CustomerOrdersManageRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerCartRoute: CustomerCartRoute,
  CustomerCheckoutRoute: CustomerCheckoutRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerOrdersOrderIdRoute: CustomerOrdersOrderIdRoute,
  CustomerOrdersManageRoute: CustomerOrdersManageRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
